### ISSUE TITLE
jumping led to an interesting discovery.. problem invoking with paladin

### ISSUE THREAD

**Issue by mystixa** [BigRedBot/NeverwinterInvokeBot#21]
So I have ru the invoker on my main character a few times successfuly. A standard CW. 

I decided to try and setup my 3 characters that I use on the invoker. I discovered that it works just fine on characters 1 and 3, the CW, and TR, but not on character 2 my paly. I can only guess its because something is slightly different in the display.

I'm not sure how to go about fixing this.

**Comment by mystixa** [comment]
oh yes.. so the symptom on the paladin btw is constant jumping.

**Comment by BigRedBrent** [comment]
You could try resetting the Paladin's user interface windows to default. Rearrange HUD then use Shift+Escape keys.

**Comment by mystixa** [comment]
ok ill give it a try.. It should be at default, as Ive never changed his settings, but you never know. 

Ive confirmed that it is not detecting it by a pretty ugly method. At line 490 I lied to it and put in a 'Return 1', essentially telling it the game was running. With that everything went smoothly. Why this? Im still wrapping my head around how _imagesearcharea works.
