### ISSUE TITLE
Char names/numbers instead of a percentage of completion

### ISSUE THREAD

**Issue by Lunarcy12** [BigRedBot/NeverwinterInvokeBot#22]
Is there any way for the script to list the names or numbers of the chars that did not invoke?  If you have a lot of them, its difficult to tell which one has something in overflow or is off the invoke point.  It would certainly narrow down the hunt.

**Comment by BigRedBrent** [comment]
The script currently is not sure what character it invoked on because it can make mistakes due to system lag, it only knows that it did invoke. It uses this number to try to determine if you have finished invoking or not.

**Comment by BigRedBrent** [comment]
I like to use the profession bot to keep track of items. I add the items I want to track in the custom tracked resources tab.

Green Vitriol = Crafting_Resource_Vitriol_Green
Blue Vitriol = Crafting_Resource_Vitriol_Blue

Coalescent Ward = Fuse_Ward_Coalescent_Invocation
Preservation Ward = Fuse_Ward_Preservation_Invocation

Greater Mark of Power = Artifact_Upgrade_Resource_R3_A
Greater Mark of Stability = Artifact_Upgrade_Resource_R3_B
Greater Mark of Union = Artifact_Upgrade_Resource_R3_C

Mark of Power = Artifact_Upgrade_Resource_R2_A
Mark of Stability = Artifact_Upgrade_Resource_R2_B
Mark of Union = Artifact_Upgrade_Resource_R2_C

Lesser Mark of Power = Artifact_Upgrade_Resource_R1_A
Lesser Mark of Stability = Artifact_Upgrade_Resource_R1_B
Lesser Mark of Union = Artifact_Upgrade_Resource_R1_C

Greater Resonance Stone = Artifactgear_Food_R4_A
Resonance Stone = Artifactgear_Food_R3_A
Lesser Resonance Stone = Artifactgear_Food_R2_A
Minor Resonance Stone = Artifactgear_Food_R1_A

Greater Thaumaturgic Stone = Gemfood_Stone_R4
Thaumaturgic Stone = Gemfood_Stone_R3
Lesser Thaumaturgic Stone = Gemfood_Stone_R2
Minor Thaumaturgic Stone = Gemfood_Stone_R1

Black Opal = Gemfood_R5
Flawless Sapphire = Gemfood_R4
Aquamarine = Gemfood_R3
Peridot = Gemfood_R2
White Pearl = Gemfood_R1

Greater Power Stone = Artifactfood_R4_A
Power Stone = Artifactfood_R3_A
Lesser Power Stone = Artifactfood_R2_A
Minor Power Stone = Artifactfood_R1_A

Greater Stability Stone = Artifactfood_R4_B
Stability Stone = Artifactfood_R3_B
Lesser Stability Stone = Artifactfood_R2_B
Minor Stability Stone = Artifactfood_R1_B

Greater Union Stone = Artifactfood_R4_C
Union Stone = Artifactfood_R3_C
Lesser Union Stone = Artifactfood_R2_C
Minor Union Stone = Artifactfood_R1_C

Tome of Experience = Item_Potion_Xp_Account

**Comment by noonereally** [comment]
If I understand correctly i does select the char by the current index and knows to select the next one and so on. So perhaps a 'full detail' setting that can be enabled or disabled  that will show a more detailed screen at the end with all char numbers, if it invoked, collected the coffer and so on.
Even if not 100% accurate.

If you want to integrate it a bit, we can add a settings exporter in the professions script, that will have all the settings set to defaults but modifiable, so people can click export and get the ini file with the char names, so the invoke script can display them.

**Comment by noonereally** [comment]
> I like to use the profession bot to keep track of items. I add the items I want to track in the custom tracked resources tab.

Looks like a very complete list, maybe it should replace the default that there is now.

**Comment by BigRedBrent** [comment]
That list is missing the marks of potency. I would like to add those as well.

**Comment by Lunarcy12** [comment]
>If I understand correctly it does select the char by the current index and knows to select the next one >and so on. So perhaps a 'full detail' setting that can be enabled or disabled that will show a more >detailed screen at the end with all char numbers, if it invoked, collected the coffer and so on.
>Even if not 100% accurate.
>
>If you want to integrate it a bit, we can add a settings exporter in the professions script, that will have >all the settings set to defaults but modifiable, so people can click export and get the ini file with the >char names, so the invoke script can display them.

Yes pls

**Comment by BigRedBrent** [comment]
I added the marks of potency to that list.
