### ISSUE TITLE
Problem with Invocation

### ISSUE THREAD

**Issue by crnacsrb** [BigRedBot/NeverwinterInvokeBot#25]
Hi.
I use InvocationBot, ussually at night, while I'm sleeping. When I do Invocation by myself, it takes ~ 30 min for all charachter, and bot do it for ~ 60 min. That is why I'm using it by night. But problem is, that sometimes when I woke up and check it, he done it by loop 5-6, and sometime he don't even pass loop 1. Or sometime couple of first charachters are at loop 3, and plenty of other charachters are not even pass loop 1. Sometime, I found account loged out (because of 15 min of inactivity).
Btw, 95% of my charachters are TR, and I have a VIP lvl 6, so I can do Invocation anywhere on map.

Do You know any reason why that is happening, or even better - what can I do, to fix it?

Thank You.

**Comment by BigRedBrent** [comment]
Not sure. Try resetting the hud on all of your characters. Perhaps watch it and see when it messes up.
