### ISSUE TITLE
how to reduce the time in script

### ISSUE THREAD

**Issue by crnacsrb** [BigRedBot/NeverwinterInvokeBot#29]
Hi.
I still have problems which I've explain it before, but even with that - I like script very much. 
But, I have 50 charachters, and invoking take about 6 hours to complete. 
How can I edit the script to short delay times, specially when script load the charachter, and wait until invoke?
And when invoke is done (and there is reward screen on), then its wait too long to press Escape to delete them and starting log out with that charachter?

I don't know anything about programing, so if You can explain me, or just write number of lines where I need to change numbers.....I will be very thankful. :)

Thank You.

**Comment by BigRedBrent** [comment]
It might save maybe a minute total if you shaves a little time off of the delay. Even with over 50 characters. There is a delay in between invoke loops that can not be avoided because that is imposed in game.
