### ISSUE TITLE
Invoke bot seems to get stuck on collecting Coffer of Celestial Artifact Equipment

### ISSUE THREAD

**Issue by One2nv** [BigRedBot/NeverwinterInvokeBot#30]
#Hi there, since Maze Engine, the script seem to struggle to select the "Celestial Synergy" tab in the Vault of Piety.  When the window opens its showing the first tab "Ardent Favor" and just keep trying to switch tabs until eventually it times out.  This was working beautifully before the last MOD.  Any ideas as to what changed or how to fix?  Is anyone else also seeing this now? Currently using version 3.30.3

**Comment by shonsu02** [comment]
I saw the same thing.  I downloaded the latest version and overwrote all files in the directory and it works fine now.

**Comment by One2nv** [comment]
Thanks.  I'll try that.  I just noticed the change log notes for 3.37 - updated  Celestial Synergy tab
