### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by supirio** [BigRedBot/NeverwinterInvokeBot#63]
Hi, I am having some trouble when it gets to "Waiting for Character Select Screen", it just sits there waiting even though it is already on the Character Select Screen.  I thought maybe it had something to do with my monitor resolution (1440p), but then I realized it is resizing the window anyway.  I'm sure I am just not doing something right, any help on how to troubleshoot this is appreciated.  Thank you!

**Comment by h3llhound** [comment]
It does that to me, load up the game then log out from the character selection screen, then open the bot up, will run all invokes no problem. At least for me it worked anyways

**Comment by UrbanDK** [comment]
I had this issue on a dual monitor windows 10 x64 system.  I moved over to a windows 10 x64 laptop (one monitor) and it worked just fine.  Are you on a system with dual monitors?  try removing one.
